### ISSUE TITLE
it's slow

### ISSUE THREAD

**Issue by GregorStocks** [GregorStocks/shirt#4]
it is slow

**Comment by j-po** [comment]
What part? How do I repro?

**Comment by GregorStocks** [comment]
Run `make` (which generates 10 pngs) - it'll take like 5 minutes

**Comment by j-po** [comment]
You just want me to do profiling research so you don't have to...

**Comment by GregorStocks** [comment]
Yes

**Comment by j-po** [comment]
Generating a badness profile for each candidate is responsible for most of the wackness (two-thirds of said wackness coming from the distance from width metric), followed by generating candidates and sorting by badness, which are each about a third as wack as that.

**Comment by j-po** [comment]
```
                    pId      nCalls       Min        Max       MAD      Mean   Time% Time
                :render          12    1.18ms     45.51s    10.51s     15.9s      97 190.78s
           :render-text          10     6.97s     45.36s    10.24s    18.92s      96 189.15s
       :best-partitions          85     1.21s     17.53s     1.18s     2.22s      96 189.11s
       :sort-candidates          85     1.21s     17.53s     1.18s     2.22s      96 189.11s
       :general-badness   4,187,650   11.58μs      2.65s    8.78μs    26.7μs      57 111.81s
   :candidate-partition     212,500   34.57μs   297.31ms  397.82μs  351.08μs      38 74.6s
:width-coverage-badness   4,187,650    4.63μs      2.65s    7.25μs   17.04μs      36 71.34s
        :height-badness   4,187,650    1.33μs    54.52ms     400ns    2.34μs       5 9.78s
          :total-height   4,187,650     483ns    23.54ms     158ns    1.03μs       2 4.3s
            :load-image          10    5.43ms    79.03ms   13.03ms   13.85ms       0 138.55ms
             Clock Time                                                          100 197.65s
         Accounted Time                                                          521 1030.14s
```

**Comment by j-po** [comment]
Hey, @GregorStocks, did you know that `sort-by` doesn't guarantee calling the key function once per element? Funny story there.

**Comment by j-po** [comment]
(Patch coming momentarily.)

**Comment by j-po** [comment]
See PR #6

**Comment by j-po** [comment]
```
                    pId      nCalls       Min        Max       MAD      Mean   Time% Time
                :render          12    1.22ms     16.84s     4.45s     7.67s      93 92.06s
           :render-text          10     2.08s     16.67s     3.82s     9.05s      91 90.45s
       :best-partitions          85  225.45ms     16.67s     1.13s     1.06s      91 90.38s
   :candidate-partition     212,500   39.66μs      1.17s  449.42μs  389.57μs      83 82.78s
       :general-badness     212,500   14.62μs    54.42ms    8.66μs   29.35μs       6 6.24s
:width-coverage-badness     212,500    6.41μs    54.38ms    6.62μs   18.52μs       4 3.93s
        :height-badness     212,500    2.02μs   417.49μs    1.02μs    3.39μs       1 719.72ms
          :total-height     212,500     656ns    68.26μs     191ns    1.21μs       0 256.06ms
            :load-image          10    5.34ms    70.96ms    11.7ms   12.47ms       0 124.73ms
             Clock Time                                                          100 99.41s
         Accounted Time                                                          369 366.95s
```

**Comment by GregorStocks** [comment]
Not shocked that finding the right candidate is where the lion's share of the time goes. The current algorithm is something like the following (I'm not, like, looking at the code right now or anything):

- Choose an enormous number of candidates (a candidate is a set of positions for linebreaks to go on)
- For each candidate, render the best possible shirt and calculate its badness. The best possible shirt for that candidate is currently one which renders each line as tall as possible, except that line n of m cannot go below (n/m * height) down the shirt. If a line would overflow we reduce the font size - the next line will have more vertical room so its base font size will be higher. The badness of a shirt is I think just how much horizontal underflow there is on the lines that get shrunk.
- Output the candidate with the lowest badness.

The reason it's so slow is that we're generating an enormous number of candidates. Probably most of them are ridiculous right now. If we can figure out a way to consider fewer candidates while generating better shirts, we can presumably increase the speed.

**Comment by j-po** [comment]
What do you mean by "better" and how do you plan to reconcile that need
with reducing the number of ridiculous shirts? (Also, btw, I'm working on
post-to-tumblr functionality, but feel free to veto that).

**Comment by j-po** [comment]
Like, if I may bend kayfabe for a moment here, one sensible optimization might be for the badness metric to include the std-dev of font sizes, but then we'd miss out on such masterpieces as these two:
![quotes-four](https://cloud.githubusercontent.com/assets/3677798/18306766/2bdfb068-74a2-11e6-8856-d2a0082fe5be.png)
![quotes-two](https://cloud.githubusercontent.com/assets/3677798/18306773/365c6252-74a2-11e6-8a9f-e501ad6a0868.png)

**Comment by GregorStocks** [comment]
it's pretty fast now because i improved the rendering enough that we don't need to try thousands of candidates
